language: python

matrix:
  include:
    - python: 2.7
    - python: 3.6
    - python: 3.7     # see: https://github.com/travis-ci/travis-ci/issues/9815
      dist: xenial
      sudo: true

install:
  - pip install -e .

script:
  - ./tests.sh
